## Red Alert: Omarchy Edition -- generated by tools/build_text.py from tools/roster.py.
## Keys are prefixed so they can never collide with the mod bundle (which wins on collisions).

## Factions
faction-omarchians =
    .name = Omarchians

faction-commies =
    .name = The Commies

## Owner row of enemy tooltips (the scripted enemy is a bot)
commie-bot =
    .name = The Commies

## Omarchians
omarchy-mcv =
    .name = Boot USB
    .description = Deploys into the ISO. Don't lose it.

omarchy-fact =
    .name = The ISO
    .description = Everything is built from here. Do not rm -rf.

omarchy-powr =
    .name = Hyprland
    .description = The compositor. Tiling only.

omarchy-apwr =
    .name = Hyprland (NVIDIA)
    .description = Twice the power. Check the driver. Check it again.

omarchy-proc =
    .name = Package Mirror
    .description = Refines packages into credits. Rolling release.

omarchy-silo =
    .name = Package Cache
    .description = /var/cache/pacman/pkg. Never cleaned.

omarchy-tent =
    .name = Omarchy Menu
    .description = Super + Space. Everything comes out of here.

omarchy-weap =
    .name = Docker
    .description = Ships armour in containers. Super + Shift + D for Lazydocker.

omarchy-dome =
    .name = Omarchy Bar
    .description = Always on screen. The right and middle buttons are where the good stuff hides.

omarchy-fix =
    .name = omarchy reinstall
    .description = Reinstalls the defaults and downgrades whatever is too new.

omarchy-atek =
    .name = Neovim
    .description = (btw). Unlocks everything, once you learn the keys.

omarchy-pdox =
    .name = Edge Channel
    .description = Chronoshifts units to tomorrow's packages. They come back when the snapshot restores.

omarchy-gap =
    .name = Lock Screen
    .description = Super + Ctrl + L. Nobody sees what's behind it. Fingerprint optional.

omarchy-pbox =
    .name = ufw
    .description = Default deny. Docker gets special treatment.

omarchy-hbox =
    .name = Fido2 Key
    .description = Small. Easy to miss. Denies sudo to strangers.

omarchy-gun =
    .name = sudo
    .description = Asks for your password. Then shoots.

omarchy-agun =
    .name = Silence Notifications
    .description = Super + Ctrl + , . Shoots down anything that pops up.

omarchy-sbag =
    .name = Pane Divider
    .description = Ctrl + Space, then split. Cheap. Infantry walk around it.

omarchy-fenc =
    .name = Window Gaps
    .description = Super + Shift + Backspace toggles them.

omarchy-brik =
    .name = Window Border
    .description = 2 px. Theme-coloured. Impassable.

omarchy-hpad =
    .name = Agent Terminal
    .description = Super + Shift + Ctrl + A. Launches your default agent.

omarchy-mslo =
    .name = rm -rf /
    .description = --no-preserve-root. You were warned.

omarchy-e1 =
    .name = Keybinder
    .description = Everything happens via the keyboard. EVERYTHING.

omarchy-e3 =
    .name = ripgrep
    .description = rg. Finds anything at range and hits it.

omarchy-e6 =
    .name = chown -R
    .description = Takes ownership of any building. Recursively.

omarchy-medi =
    .name = Night Light
    .description = Super + Ctrl + N. Heals the eyes of nearby operatives.

omarchy-mech =
    .name = Lazydocker
    .description = Repairs containers. Press ? for help.

omarchy-spy =
    .name = Private Window
    .description = Disguises as anything. Leaves no history.

omarchy-thf =
    .name = yt-dlp
    .description = Steals the whole thing. Lands in ~/Videos.

omarchy-e7 =
    .name = DHH
    .description = One per distribution. Do not let him near the config.

omarchy-jeep =
    .name = Alacritty
    .description = Fast. Minimal. GPU-accelerated.

omarchy-1tnk =
    .name = Foot
    .description = The default. Fast, lightweight, runs on old hardware. No tabs.

omarchy-2tnk =
    .name = Ghostty
    .description = Optional. Heavier. Has tabs.

omarchy-arty =
    .name = LocalSend
    .description = Lobs files across the network. Super + Ctrl + S.

omarchy-apc =
    .name = Workspace
    .description = Carries five windows. Super + Shift + 2 moves them.

omarchy-mnly =
    .name = Reminders
    .description = Lays timed messages. They go off later. Super + Ctrl + R.

omarchy-ctnk =
    .name = zoxide
    .description = Remembers everywhere it's been. Jumps there.

omarchy-mgg =
    .name = Screensaver
    .description = ASCII art on wheels. Hides everything behind it.

omarchy-harv =
    .name = omarchy update
    .description = Harvests packages the right way. Takes a snapshot first. Alias: mup.

omarchy-heli =
    .name = Coding Agent
    .description = Auto-approving mode. Rockets included. What could go wrong.

omarchy-tran =
    .name = Tmux
    .description = Carries five panes anywhere. Ctrl + Space is the prefix.

omarchy-mh60 =
    .name = Herdr
    .description = Like Tmux, newer. Detach, come back later, it is still running.

omarchy-mrj =
    .name = Hide Bar
    .description = Super + Shift + Space. Their radar goes blank.

## Omarchian support powers
omarchy-power-pdox =
    .name = Edge Channel
    .description = Sends units to the edge channel. The snapshot brings them back.

omarchy-power-mslo =
    .name = rm -rf /
    .description = --no-preserve-root. You were warned.

## The Commies
commie-fact =
    .name = Central Planning Compositor
    .description = All windows shall float.

commie-powr =
    .name = Snap Daemon
    .description = Provides power. Runs at boot whether you asked or not.

commie-apwr =
    .name = Flatpak Runtime
    .description = Provides power. 3 GB of runtimes included.

commie-barr =
    .name = The Forum
    .description = Trains cadres. Please search before posting.

commie-weap =
    .name = Electron Factory
    .description = Every unit ships with its own browser.

commie-dome =
    .name = Telemetry Dome
    .description = Sees everything you do. The opt-out is buried.

commie-fix =
    .name = Support Ticket
    .description = Repairs in 3 to 5 business days.

commie-stek =
    .name = Design Committee
    .description = Unlocks features nobody asked for.

commie-kenn =
    .name = systemd
    .description = Breeds Hounds. Also handles logging, networking, time and your init.

commie-iron =
    .name = Five-Year Plan
    .description = All windows will float. It is only a matter of time.

commie-ftur =
    .name = Flame War
    .description = Burns anyone who mentions systemd.

commie-sam =
    .name = CAPTCHA
    .description = Shoots down anything that looks automated.

commie-afld =
    .name = App Store
    .description = Launches Windows Updates.

commie-mslo =
    .name = Forced Reboot
    .description = Updates are ready. Restart now.

commie-brik =
    .name = Paywall
    .description = Subscribe to pass.

commie-e1 =
    .name = Party Cadre

commie-e2 =
    .name = Hot Take
    .description = Lobs opinions. Splash damage.

commie-e3 =
    .name = Reply Guy
    .description = Well, actually. Long range.

commie-e4 =
    .name = Flame Warrior

commie-shok =
    .name = Moderator
    .description = Shocks. Bans. Locks the thread.

commie-e6 =
    .name = Consultant
    .description = Captures your buildings. Bills hourly.

commie-dog =
    .name = Systemd Hound

commie-spy =
    .name = Tracking Pixel

commie-3tnk =
    .name = Floating Window
    .description = Slow. Overlaps everything.

commie-4tnk =
    .name = GNOME Shell
    .description = Invulnerable, as usual.

commie-v2rl =
    .name = Electron App
    .description = 400 MB. Hits your RAM from across the map.

commie-ftrk =
    .name = Cookie Banner
    .description = Pops up. Blocks everything until you click Accept.

commie-ttnk =
    .name = KDE Plasma
    .description = Every widget. All of them. At once.

commie-apc =
    .name = Floating Dialog

commie-mnly =
    .name = Update Notifier
    .description = Lays reminders you didn't ask for.

commie-mcv =
    .name = Distro Hopper
    .description = Deploys a new base every weekend.

commie-harv =
    .name = Data Harvester

commie-mig =
    .name = Windows Update
    .description = Arrives uninvited. Reboots what it hits.

commie-yak =
    .name = Clippy
    .description = It looks like you're trying to defend a base.

commie-hind =
    .name = Notification Spam

commie-badr =
    .name = Onboarding Wizard
    .description = Drops Next, Next, Next, Finish.

## Decoration
omarchy-sign =
    .name = Omarchy

## Objectives
omarchy-objective-compositor = Destroy the Central Planning Compositor before the Five-Year Plan completes
omarchy-objective-iso = Keep the ISO alive
omarchy-objective-plan = Cancel the Five-Year Plan (destroy the Iron Curtain)

## Message prefixes
omarchy-prefix-cpc = Central Planning Compositor
omarchy-prefix-omarchy = Omarchy

## Timed beats
omarchy-msg-decree = Decree 1: all windows shall float. Tiling is counter-revolutionary.
omarchy-msg-hounds = Incoming: Systemd Hounds detected. They want the truck.
omarchy-msg-wave1 = Floating Windows are drifting toward the ford. Close them.
omarchy-msg-reinforce = The maintainers have sent tanks. Modal drivers included.
omarchy-msg-dhh = DHH has arrived. He has opinions. Do not let him near the config.
omarchy-msg-dhh-dead = DHH has left the chat.
omarchy-msg-plan60 = The Five-Year Plan is 60% complete.
omarchy-msg-gnome = GNOME Shell is invulnerable, as usual.
omarchy-msg-gnome-cancelled = The Five-Year Plan was cancelled. GNOME Shell arrives merely annoying.
omarchy-msg-wave3 = Everything the Committee has left is coming. Both routes.
omarchy-msg-plan-done = The Five-Year Plan is complete. All windows float. Forever.
omarchy-msg-plan-cancelled = Five-Year Plan cancelled. The clock is gone. Take your time.
omarchy-msg-bridge = The bridge is down. Somebody force-pushed to main.
omarchy-msg-win = Windows are tiled. Order is restored.
omarchy-msg-lose = The ISO is gone. Reinstall from scratch.

## Reactive: our side
omarchy-msg-truck-lost = Transaction interrupted. Run omarchy update again.
omarchy-msg-agent-first = Coding Agent launched. Auto-approving mode. Keep an eye on it.
omarchy-msg-agent-lost = The agent hit its usage limit. Try again in five hours.
omarchy-msg-infantry-lost-1 = Segmentation fault (core dumped).
omarchy-msg-infantry-lost-2 = Killed by the OOM killer.
omarchy-msg-infantry-lost-3 = Keybinding unbound.
omarchy-msg-vehicle-lost-1 = Container stopped. Exit code 137.
omarchy-msg-vehicle-lost-2 = Process exited. No core file.
omarchy-msg-powr-lost = Hyprland crashed. The windows are still tiled. They are just dark.
omarchy-msg-proc-lost = Package Mirror offline. Check your mirrorlist.
omarchy-msg-tent-lost = Omarchy Menu closed. Super + Space does nothing now.
omarchy-msg-weap-lost = Docker daemon stopped. Nothing ships.
omarchy-msg-sign-lost = They painted over the logo. That one hurt.

## Reactive: their side
omarchy-msg-cpowr-lost = snapd stopped. Boot is forty seconds faster already.
omarchy-msg-capwr-lost = Flatpak Runtime removed. Three gigabytes freed.
omarchy-msg-barr-lost = The Forum is down. Thread locked.
omarchy-msg-cweap-lost = Electron Factory destroyed. RAM levels returning to normal.
omarchy-msg-cdome-lost = Telemetry Dome destroyed. You have opted out.
omarchy-msg-cfix-lost = Support Ticket closed: Won't fix.
omarchy-msg-kenn-lost = systemd unit failed. It will restart. It always restarts.
omarchy-msg-stek-lost = Design Committee dissolved. Features nobody asked for: cancelled.
omarchy-msg-tsla-lost = Tesla Coil down. Admittedly cool while it lasted.
omarchy-msg-ftur-lost = Flame War extinguished. Nobody won.
omarchy-msg-sam-lost = CAPTCHA solved. You are not a robot.
