#!/usr/bin/env python3
"""Build OpenRA's sidebar/command-bar regions from Omarchy UI surfaces."""
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'mod/ui'
INK = '#151b1a'
PANEL = '#202a23'
RAISED = '#344334'
BORDER = '#617b53'
LIME = '#9ece6a'
MUTED = '#3c4d3d'


def build():
    sheet = Image.new('RGBA', (1024, 512), (0, 0, 0, 0))
    draw = ImageDraw.Draw(sheet)

    def plate(x, y, w, h, fill=PANEL, border=BORDER):
        draw.rectangle((x, y, x + w - 1, y + h - 1), fill=fill, outline=border)
        draw.line((x + 2, y + 2, x + w - 3, y + 2), fill=MUTED)

    # Native OpenRA sidebar surfaces. Coordinates are disjoint, so image
    # regions can retain the exact engine sizes without resampling.
    plate(0, 0, 238, 262)
    plate(8, 38, 222, 222, fill=INK, border=MUTED)
    draw.line((10, 39, 227, 39), fill=LIME, width=2)
    plate(0, 264, 238, 28, fill=INK)
    draw.rectangle((2, 268, 4, 288), fill=LIME)
    plate(0, 296, 190, 47, fill=INK, border=MUTED)
    for x in (3, 65, 127):
        draw.rectangle((x, 299, x + 59, 339), outline=MUTED)
    # This region is painted *over* the production sprites by OpenRA.
    # Keep the cell interiors transparent or the buildings disappear.
    draw.line((41, 348, 237, 348), fill=MUTED)
    draw.line((41, 394, 237, 394), fill=MUTED)
    draw.line((41, 349, 41, 393), fill=MUTED)
    plate(0, 400, 238, 8, fill=INK, border=MUTED)
    plate(240, 148, 64, 48, fill=INK, border=MUTED)
    plate(256, 0, 434, 44, fill=INK)
    draw.rectangle((260, 3, 685, 5), fill=MUTED)
    draw.rectangle((260, 40, 685, 41), fill=MUTED)
    draw.rectangle((260, 3, 286, 5), fill=LIME)

    # The pause menu's border extends 15 px outside the viewport. Put the
    # visible strokes just inside that crop, instead of inheriting RA red.
    draw.rectangle((720, 16, 767, 63), outline=BORDER, width=2)
    draw.line((722, 17, 741, 17), fill=LIME, width=2)

    states = {
        'normal': (256, 64, RAISED, BORDER),
        'hover': (288, 64, '#354b32', LIME),
        'highlighted': (320, 64, '#3e5436', LIME),
        'highlighted-hover': (352, 64, '#4a6340', LIME),
        'disabled': (384, 64, '#202923', '#374333'),
    }
    for x, y, fill, border in states.values():
        plate(x, y, 28, 28, fill, border)
    sheet.save(OUT / 'omarchy-hud.png', optimize=True)

    regions = {
        'background-top': (0, 0, 238, 262),
        'background-moneybin': (0, 264, 238, 28),
        'background-iconbg': (0, 296, 190, 47),
        'background-iconrow': (0, 348, 238, 47),
        'background-bottom': (0, 400, 238, 8),
        'background-supportoverlay': (240, 148, 64, 48),
        'radar': (0, 0, 222, 222),
    }
    lines = ['# Generated by tools/build_hud_chrome.py.', '^OmarchyHud:', '\tImage: omarchy-hud.png', '']
    for faction in ('allies', 'soviet'):
        lines += [f'sidebar-{faction}:', '\tInherits: ^OmarchyHud', '\tRegions:']
        lines += [f'\t\t{name}: {", ".join(map(str, region))}' for name, region in regions.items()]
        lines += ['']
    lines += ['commandbar:', '\tInherits: ^OmarchyHud', '\tRegions:', '\t\tbackground: 256, 0, 434, 44', '']
    lines += ['mainmenu-border:', '\tInherits: ^OmarchyHud',
              '\tPanelRegion: 704, 0, 18, 18, 44, 44, 18, 18',
              '\tPanelSides: Edges', '']
    for faction in ('allies', 'soviet'):
        for kind in ('sidebar-button', 'command-button'):
            for state, (x, y, _, _) in states.items():
                suffix = '' if state == 'normal' else f'-{state}'
                lines += [f'{kind}-{faction}{suffix}:', '\tInherits: ^OmarchyHud',
                          f'\tPanelRegion: {x}, {y}, 4, 4, 20, 20, 4, 4']
                if kind == 'command-button':
                    lines += ['\tPanelSides: Center']
                lines += ['']
    (OUT / 'hud.yaml').write_text('\n'.join(lines))

if __name__ == '__main__':
    build()
