#!/usr/bin/env python3
"""
Generates omarchy.ftl, rules.yaml and sequences.yaml from tools/roster.py.

Every YAML key emitted here is copied from a shipped mission or the trait
docs of release-20250330: Tooltip.Name, Buildable.Description,
Buildable.Prerequisites (~disabled idiom from allies-02), TooltipDescription
(campaign-tooltips.yaml), RenderSprites.Image (E7.noautotarget), Mobile.Speed,
NukePower/ChronoshiftPower Name+Description (structures.yaml), the World
traits used by allies-01/02 (LuaScript, MissionData, TimeLimitManager) and
Faction.Name (world.yaml).
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import roster  # noqa: E402

BRIEFING = (
    "Comrade DHH has fled. The Central Planning Compositor has decreed that all windows shall float, "
    "and the Five-Year Plan that makes it permanent completes in thirty minutes.\\n\\n"
    "Establish the ISO, sync your packages, and destroy the Compositor before then. "
    "Destroying the Five-Year Plan itself cancels the clock.\\n\\n"
    "The Commies hold the far side of the river. One ford, one pontoon bridge. Both are watched. "
    "This isn't a grab bag of preinstalled units: zero bloat, just everything you need."
)

# Mission strings used by omarchy.lua (keys are referenced there verbatim).
MESSAGES = """
## Objectives
omarchy-objective-compositor = Destroy the Central Planning Compositor before the Five-Year Plan completes
omarchy-objective-iso = Keep the ISO alive
omarchy-objective-plan = Cancel the Five-Year Plan (destroy the Iron Curtain)

## Message prefixes
omarchy-prefix-cpc = Central Planning Compositor
omarchy-prefix-omarchy = Omarchy

## Timed beats
omarchy-msg-decree = Decree 1: all windows shall float. Tiling is counter-revolutionary.
omarchy-msg-hounds = Incoming: Systemd Hounds detected. They want the truck.
omarchy-msg-wave1 = Floating Windows are drifting toward the ford. Close them.
omarchy-msg-reinforce = The maintainers have sent tanks. Modal drivers included.
omarchy-msg-dhh = DHH has arrived. He has opinions. Do not let him near the config.
omarchy-msg-dhh-dead = DHH has left the chat.
omarchy-msg-plan60 = The Five-Year Plan is 60% complete.
omarchy-msg-gnome = GNOME Shell is invulnerable, as usual.
omarchy-msg-gnome-cancelled = The Five-Year Plan was cancelled. GNOME Shell arrives merely annoying.
omarchy-msg-wave3 = Everything the Committee has left is coming. Both routes.
omarchy-msg-plan-done = The Five-Year Plan is complete. All windows float. Forever.
omarchy-msg-plan-cancelled = Five-Year Plan cancelled. The clock is gone. Take your time.
omarchy-msg-bridge = The bridge is down. Somebody force-pushed to main.
omarchy-msg-win = Windows are tiled. Order is restored.
omarchy-msg-lose = The ISO is gone. Reinstall from scratch.

## Reactive: our side
omarchy-msg-truck-lost = Transaction interrupted. Run omarchy update again.
omarchy-msg-agent-first = Coding Agent launched. Auto-approving mode. Keep an eye on it.
omarchy-msg-agent-lost = The agent hit its usage limit. Try again in five hours.
omarchy-msg-infantry-lost-1 = Segmentation fault (core dumped).
omarchy-msg-infantry-lost-2 = Killed by the OOM killer.
omarchy-msg-infantry-lost-3 = Keybinding unbound.
omarchy-msg-vehicle-lost-1 = Container stopped. Exit code 137.
omarchy-msg-vehicle-lost-2 = Process exited. No core file.
omarchy-msg-powr-lost = Hyprland crashed. The windows are still tiled. They are just dark.
omarchy-msg-proc-lost = Package Mirror offline. Check your mirrorlist.
omarchy-msg-tent-lost = Omarchy Menu closed. Super + Space does nothing now.
omarchy-msg-weap-lost = Docker daemon stopped. Nothing ships.
omarchy-msg-sign-lost = They painted over the logo. That one hurt.

## Reactive: their side
omarchy-msg-cpowr-lost = snapd stopped. Boot is forty seconds faster already.
omarchy-msg-capwr-lost = Flatpak Runtime removed. Three gigabytes freed.
omarchy-msg-barr-lost = The Forum is down. Thread locked.
omarchy-msg-cweap-lost = Electron Factory destroyed. RAM levels returning to normal.
omarchy-msg-cdome-lost = Telemetry Dome destroyed. You have opted out.
omarchy-msg-cfix-lost = Support Ticket closed: Won't fix.
omarchy-msg-kenn-lost = systemd unit failed. It will restart. It always restarts.
omarchy-msg-stek-lost = Design Committee dissolved. Features nobody asked for: cancelled.
omarchy-msg-tsla-lost = Tesla Coil down. Admittedly cool while it lasted.
omarchy-msg-ftur-lost = Flame War extinguished. Nobody won.
omarchy-msg-sam-lost = CAPTCHA solved. You are not a robot.
"""


def ftl():
    out = ["## Red Alert: Omarchy Edition -- generated by tools/build_text.py from tools/roster.py.",
           "## Keys are prefixed so they can never collide with the mod bundle (which wins on collisions).", ""]
    out += ["## Factions", f"faction-omarchians =\n    .name = {roster.FACTIONS['allies']}", "",
            f"faction-commies =\n    .name = {roster.FACTIONS['soviet']}", "",
            "## Owner row of enemy tooltips (the scripted enemy is a bot)",
            f"commie-bot =\n    .name = {roster.BOT_NAME}", ""]
    out.append("## Omarchians")
    for actor, name, desc, _role in roster.OMARCHY:
        s = f"omarchy-{actor} =\n    .name = {name}"
        if desc:
            s += f"\n    .description = {desc}"
        out += [s, ""]
    out.append("## Omarchian support powers")
    for actor, (_trait, name, desc) in roster.OMARCHY_POWERS.items():
        out += [f"omarchy-power-{actor} =\n    .name = {name}\n    .description = {desc}", ""]
    out.append("## The Commies")
    for actor, name, desc, _role in roster.COMMIE:
        s = f"commie-{actor} =\n    .name = {name}"
        if desc:
            s += f"\n    .description = {desc}"
        out += [s, ""]
    out += ["## Decoration", "omarchy-sign =\n    .name = Omarchy", ""]
    out.append(MESSAGES.strip() + "\n")
    return "\n".join(out)


def rules():
    out = []
    out.append(f"""Player:
	PlayerResources:
		DefaultCash: 1500
	ModularBot@CampaignAI:
		Name: commie-bot.name

World:
	LuaScript:
		Scripts: campaign.lua, utils.lua, omarchy.lua
	MissionData:
		Briefing: {BRIEFING}
	Faction@allies:
		Name: faction-omarchians.name
	Faction@soviet:
		Name: faction-commies.name
	TimeLimitManager:
		CountdownLabel: MISSION_TEXT
		CountdownText: Five-Year Plan completes in {{0}}
		Notification: {{0}} minute{{1}} until all windows float
		SkipTimerExpiredNotification: True
""")
    out.append("# ---- Omarchians -------------------------------------------------------\n")
    for actor, name, desc, _role in roster.OMARCHY:
        block = f"{actor.upper()}:\n\tTooltip:\n\t\tName: omarchy-{actor}.name\n"
        if desc:
            block += f"\tBuildable:\n\t\tDescription: omarchy-{actor}.description\n"
        if actor == "e7":  # one per distribution: the hero arrives by script, not from the menu
            block += "\t\tPrerequisites: ~disabled\n"
        if actor in roster.SPEED_TWEAKS:
            block += f"\tMobile:\n\t\tSpeed: {roster.SPEED_TWEAKS[actor]}\n"
        if actor in roster.OMARCHY_POWERS:
            trait, _n, _d = roster.OMARCHY_POWERS[actor]
            block += f"\t{trait}:\n\t\tName: omarchy-power-{actor}.name\n\t\tDescription: omarchy-power-{actor}.description\n"
        out.append(block)
    out.append("# ---- Omakase: not in Omarchy, not in the menu ---------------------------\n")
    for actor in roster.OMARCHY_REMOVED:
        out.append(f"{actor.upper()}:\n\tBuildable:\n\t\tPrerequisites: ~disabled\n")
    out.append("# ---- The Commies -------------------------------------------------------\n")
    for actor, name, desc, _role in roster.COMMIE:
        if actor in roster.SHARED_TYPES:
            block = (f"{actor.upper()}.COMMIE:\n\tInherits: {actor.upper()}\n"
                     f"\tTooltip:\n\t\tName: commie-{actor}.name\n"
                     f"\tBuildable:\n\t\tPrerequisites: ~disabled\n"
                     f"\tRenderSprites:\n\t\tImage: {actor}\n")
        else:
            block = f"{actor.upper()}:\n\tTooltip:\n\t\tName: commie-{actor}.name\n"
            if actor in roster.SPEED_TWEAKS:
                block += f"\tMobile:\n\t\tSpeed: {roster.SPEED_TWEAKS[actor]}\n"
        if desc:
            block += f"\tTooltipDescription:\n\t\tDescription: commie-{actor}.description\n"
        out.append(block)
    out.append("""# ---- Decoration ---------------------------------------------------------

OMARCHY.SIGN:
	Inherits@1: ^SpriteActor
	Interactable:
	Tooltip:
		Name: omarchy-sign.name
		ShowOwnerRow: false
	RenderSprites:
		Image: omarchysign
	WithSpriteBody:
	Building:
		Footprint: xxx xxx xxx
		Dimensions: 3,3
	AppearsOnRadar:
	HiddenUnderShroud:
	MapEditorData:
		Categories: Decoration
""")
    return "\n".join(out)


def sequences(icon_entries):
    out = ["omarchysign:\n\tidle:\n\t\tFilename: omarchysign.shp\n"]
    out += icon_entries
    return "\n".join(out)


if __name__ == "__main__":
    print(ftl())
    print("=" * 60)
    print(rules())
