#!/usr/bin/env python3
"""Draw exact nine-slice UI surfaces for the Omarchy mod (no stock texture edits)."""
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
STATES = {
    'dialog': ('#171b1c', '#596b48'),
    'button': ('#272e2a', '#48533f'),
    'button-hover': ('#354332', '#9ece6a'),
    'button-pressed': ('#101615', '#46533f'),
    'button-disabled': ('#202624', '#303932'),
    'button-highlighted': ('#3a5030', '#9ece6a'),
    'button-highlighted-pressed': ('#293d23', '#9ece6a'),
    'checkbox-hover': ('#354332', '#9ece6a'),
    'checkbox-disabled': ('#202624', '#303932'),
    'checkbox-highlighted': ('#3a5030', '#9ece6a'),
    'dialog4': ('#101615', '#9ece6a'),
}

def build():
    atlas = Image.new('RGBA', (256, 64), (0, 0, 0, 0))
    draw = ImageDraw.Draw(atlas)
    chrome = ['# Generated by tools/build_ui_chrome.py.\n^OmarchyPanels:\n\tImage: omarchy-panels.png\n']
    for i, (name, (fill, border)) in enumerate(STATES.items()):
        x, y = (i % 8) * 32, (i // 8) * 32
        draw.rectangle((x, y, x + 31, y + 31), fill=fill, outline=border)
        chrome.append(f'{name}:\n\tInherits: ^OmarchyPanels\n\tImage: omarchy-panels.png\n')
        if name == 'dialog':
            chrome[-1] += '\tRegions:\n' + ''.join(f'\t\t{k}: {x+a}, {y+b}, {w}, {h}\n' for k,a,b,w,h in (
                ('background',2,2,28,28),('border-r',30,2,2,28),('border-l',0,2,2,28),
                ('border-b',2,30,28,2),('border-t',2,0,28,2),('corner-tl',0,0,2,2),
                ('corner-tr',30,0,2,2),('corner-bl',0,30,2,2),('corner-br',30,30,2,2)))
        else:
            chrome[-1] += f'\tPanelRegion: {x}, {y}, 2, 2, 28, 28, 2, 2\n'
    for suffix, source in (('', 'button-highlighted'), ('-hover', 'button-hover'), ('-pressed', 'button-highlighted-pressed'), ('-disabled', 'button-disabled')):
        chrome.append(f'omarchy-primary{suffix}:\n\tInherits: {source}\n')
    atlas.save(ROOT / 'mod/ui/omarchy-panels.png', optimize=True)
    (ROOT / 'mod/ui/panels.yaml').write_text('\n'.join(chrome))

if __name__ == '__main__':
    build()
